version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    reviewers:
      - founders
    assignees:
      - founders
    commit-message:
      prefix: ci
      include: scope
    groups:
      ci-dependencies:
        patterns:
          - "*"
